/* ======================================================================== */
/* Program    :  DASYLab                                                    */
/* Module     :  HELP.H                                                     */
/* ------------------------------------------------------------------------ */
/* Created    :  J. Pfannkuch                                               */
/* ======================================================================== */

/* Help IDs for DASYLab's help file */
#define GL_KANALANZ           10030
#define MODULNAME             13020
#define MODULBESCHREIB        13030
#define KBEZEICHNUNG          14650
#define KEINHEIT              13040

/* Menue Hilfe */
#define HELP_ON_HELP           9990
#define INDEX                 10000

/* Add IDs for your own help file here */
/* i.e.: #define YOUR_HELP_ID 20001 */

/* eof */
